lr: 0.002
weight_decay: 5e-4
epochs: 50
train_batch_size: 256
test_batch_size: 1024
label_noise: 0.0
num_classes: 10
t_pool: 100
t_test: 100
weight_decay_grid: [1.0e-6, 1.0e-4, 5.0e-4, 1.0e-3]
initial_class_size: 2
val_size: 100
active_learning_points: 10
active_learning_iters: 100
use_dropout_in_acquisition: true
use_dropout_in_eval: true
diversity_lambda: 0.5
dataset: fashion_mnist
