noise_val: [0.0, 0.15]
repeats: 3
class_af: [random, entropy, bald]
regression_af: [trace, random]
regression_inference: [analytic, mfvi, vi, vi_full]
lr: 0.002
weight_decay: 5e-4
epochs: 50
train_batch_size: 256
test_batch_size: 1024
label_noise: 0.0
num_classes: 10
initial_class_size: 2
val_size: 0
dataset: mnist
t_pool: 100
t_test: 100
weight_decay_grid: [1.0e-6, 1.0e-4, 5.0e-4, 1.0e-3]
active_learning_points: 10
active_learning_iters: 100
use_dropout_in_acquisition: true
use_dropout_in_eval: true
sigma: 0.3
s: 1.0
inference_steps: 400
inference_lr: 0.05
acquire_steps: 100
acquisition_size: 10