lr: 0.002
weight_decay: 5e-4
epochs: 50
train_batch_size: 256
test_batch_size: 1024
acquire_steps: 50
acquisition_size: 10
regression_af: trace
regression_dataset: mnist
ood_regression_dataset: fashion_mnist
pool_ood_ratio: 0.3
initial_class_size: 2
val_size: 100
label_noise: 0.0
sigma: 0.3
s: 1.0
inference_steps: 800
vi_steps: 800
vi_lr: 0.005